// ❗ You don't need to add extra action types to achieve MVP
export const MOVE_CLOCKWISE = 'MOVE_CLOCKWISE'
export const MOVE_COUNTER_CLOCKWISE = 'MOVE_COUNTER_CLOCKWISE'
export const SET_QUIZ_INTO_STATE = 'SET_QUIZ_INTO_STATE'
export const SET_SELECTED_ANSWER = 'SET_SELECTED_ANSWER'
export const SET_INFO_MESSAGE = 'SET_INFO_MESSAGE'
export const INPUT_CHANGE = 'INPUT_CHANGE'
export const UPDATE_NEW_QUESTION = 'UPDATE_NEW_QUESTION'
export const UPDATE_NEW_TRUE_ANSWER = 'UPDATE_NEW_TRUE_ANSWER'
export const UPDATE_NEW_FALSE_ANSWER = 'UPDATE_NEW_FALSE_ANSWER'

export const RESET_FORM = 'RESET_FORM'

export const RESET_SELECTED_ANSWER = 'RESET_SELECTED_ANSWER'